path: data

train:
  - RoboFlow_FLIR_Dataset_v27_yolo11/train/images
  - FLUX1-Fill-dev/split_1/images
  - FLUX1-Fill-dev/split_2/images
  - FLUX1-Fill-dev/split_3/images

val: RoboFlow_FLIR_Dataset_v27_yolo11/valid/images
test: RoboFlow_FLIR_Dataset_v27_yolo11/test/images

nc: 3
names: ['car', 'dog', 'person']